### ISSUE TITLE
Support batch

### ISSUE THREAD

**Issue by trungnt13** [shawntan/theano-ctc#1]
Hi shawntan,

I tested several CTC implementation with theano, includes:
- [rakeshvar](https://github.com/rakeshvar/rnn_ctc)
- [Mohammad Pezeshki](https://github.com/mohammadpz/CTC-Connectionist-Temporal-Classification) 

And end up with the result that your implementation provide the most reliable and robust alignment. 
However, the training without batch is extremely slow and painful on GPU. For the same testing task:

| Methods | Time |
| --- | --- |
| Shawtan-CTC:**CPU** | 38s |
| Shawtan-CTC:**GPU** | 150s |
| Mohammad-CTC:**GPU** | 10s |

Is it possible to provide batch-support implementation ? If you don't have time, can you give me a hint to implement it ? 

Best Regards,
TrungNT

**Comment by shawntan** [comment]
It's not something I'm working on right now, but I'll get round to it.

In the meantime, you might wanna take a look at what @kastnerkyle has done here: https://gist.github.com/kastnerkyle/ca851e39229551208c0d

**Comment by kastnerkyle** [comment]
The one I have has issues on GPU at the moment (I based it on Mohammad's, so he might have the same problem - not sure). But it is mostly a matter of masking and annoying plumbing to move to minibatches unfortunately - the code @shawntan has shows all the core concepts perfectly!

**Comment by trungnt13** [comment]
Thank @shawntan and @kastnerkyle 

Supporting batch would be great, however, I am not fully understand the different in performance between shawntan and Mohammad implementation is because of batching or the way doing CTC.

The key point is that both 2 papers from Alex Graves (CTC:Labelling Unsegmented Sequence Data with RNN, and Sequence Transduction with RNN) trained CTC with online gradient descent (weight updates after every training example). 
Hence, it maybe critical to train CTC with online steepest descent as shawntan's code. For a sequence learning task, the different between stochastic learning and batch learning can be quite important.

However, it will be very slow, hence, do you have idea to speed up this steepest training process?

**Comment by shawntan** [comment]
Hm. One way would be, if you already know how many sequences you want to have in your minibatch, to create a really huge computational graph that does the update for those number of sequences. You would then only transfer those sequences to the GPU once, and then the updates happen on the GPU.

**Comment by trungnt13** [comment]
Thanks @shawntan 

This is my approach based on your idea:

``` python
MAX_BATCH_SIZE = 500

def get_trainer(layer, cost_func):
    floatX = theano.config.floatX

    # ====== Input variable ====== #
    all_params = lasagne.layers.get_all_params(layer, trainable=True)
    X_ = T.matrix(dtype=floatX)
    y_ = T.matrix(dtype=floatX)
    idx_ = T.ivector()

    # ====== For record the cost ====== #
    cost = theano.shared(np.zeros(MAX_BATCH_SIZE).astype(floatX)) # stupid fix
    cost_idx = theano.shared(np.arange(MAX_BATCH_SIZE).astype(np.int32))

    # ====== return updat for params ====== #
    def updater(X, y):
                # this could be any function provide prediction
        y_pred = lasagne.layers.get_output(layer, X)
        cost = cost_func(y_pred, y) # your cost function
        g = T.grad(cost, all_params)
        return cost, OrderedDict({all_params[i]: all_params[i] - 1e-2 * g[i] for i in xrange(len(all_params))})

    # ====== scan ====== #
    def step(idx1, idx2, i, X, y):
        c, update = updater(X[idx1:idx2, :], y[i,:])
                # record the cost
        update[cost] = T.set_subtensor(cost[i:], c)
        return update

    result, update = theano.scan(step,
        sequences=[dict(input=idx_, taps=(0, 1)),
                   cost_idx],
        non_sequences=[X_, y_])

    s = theano.function(inputs=[X_, y_, idx_],
        updates=update,
        allow_input_downcast=True)

    def trainer(X, y, idx):
        s(X, y, idx)
        return cost[:(len(idx) - 1)].eval()
    return trainer
```

So the data must be organized as following:
- X: is a matrix [nb_samples*input_seq_len, nb_features]
- idx: is a indicator [start_seq1, end_seq1, start_seq2, end_seq2, ...]
- y: is a matrix [nb_samples, output_seq_len]

Here is the performance after this improvement, the training time dropped by half (Note I tested on very small dataset, hence, we will get more improvement with bigger dataset):

| Methods | Time |
| --- | --- |
| CPU | 19s |
| GPU | 77s |

Plenty room for improvement, this is just initial code. 
What do you think about organizing the data ? I prefer the indicator approach, since you don't have to deal with mask.

**Comment by mbhenry** [comment]
Here's a minibatch version of Shawn's CTC using Keras.  It gets roughly a 4x speedup over the non-minibatch theano-ctc version.  The data generator class is overkill for this, but I'm using this in an image OCR application where it comes in handy.

`######
# Run with: THEANO_FLAGS=mode=FAST_RUN,device=gpu,floatX=float32,on_unused_input=ignore python ocr_keras.py

import sys
sys.path.append('/home/mbhenry/local/libs/keras/keras')

import random, string

import ctc
import font
import hinton

from keras import backend as K
from keras.layers.recurrent import LSTM
from keras.models import Sequential, Graph
from keras.layers.core import Dense, Dropout, Activation, TimeDistributedDense, Masking, LambdaMerge, Lambda, Layer, Merge
from keras.optimizers import SGD
from IPython import embed
from keras.utils import np_utils
import keras


import theano
import numpy as np

def shuffle_matrices( matrix_list, stop_ind = None):
    ret = []
    assert( all( [ len(i) == len(matrix_list[0] ) for i in matrix_list ] ) )
    len_val = len( matrix_list[0] )
    if stop_ind == None:
        stop_ind = len_val
    assert( stop_ind <= len_val ) 

    a = range( stop_ind )
    random.shuffle(a)
    a = a + range( stop_ind, len_val )
    for mat in matrix_list:
        ret.append( mat[a] )
    return ret

class DataGenerator( ):

    def __init__( self, minibatch_size ):
        self.minibatch_size = minibatch_size

    def time_to_categorical( self, Y, num_classes ):
        ret = np.zeros( [Y.shape[0], Y.shape[1], num_classes] )
        for i in range(Y.shape[0]):
            ret[i,:,:] = np_utils.to_categorical( Y[i,:], num_classes )
        return ret
    
    def get_output_size( self ):
        return len(font.chars)+1    

    def get_output_shape( self ):
        return [ None, self.get_output_size() ]

    def create_word_list( self, word_file, num_words, val_split, max_word_len = None ):
        self.word_list = []
        self.num_words = None
        
        assert( num_words % self.minibatch_size == 0 )
        assert( ( val_split * num_words ) % self.minibatch_size == 0 )

        with open(word_file, "rt") as f:
            for line in f:
                word = line.rstrip()
                if( max_word_len == -1 or max_word_len == None or len( word ) <= max_word_len ):
                    self.word_list.append( word )
                if( len( self.word_list ) == num_words ):
                    break

        self.num_words = num_words
        self.val_split = val_split

        self.X_data = np.ones( [self.num_words, max_word_len*8, 8 ] ) * -1
        self.Y_data = np.ones( [self.num_words, max_word_len ] ) * -1
        self.X_len = [0] * self.num_words
        self.Y_len = [0] * self.num_words

        for i, word in enumerate( self.word_list):

            self.X_len[i] = ( len( word ) ) * 8
            self.X_data[i, 0:self.X_len[i], :] = font.imagify( word )
            self.Y_len[i] = len( word ) 
            self.Y_data[i, 0:self.Y_len[i] ] = font.indexify( word )

        self.Y_data = self.time_to_categorical( self.Y_data, self.get_output_size() )
        self.X_len = np.expand_dims( np.array( self.X_len ), 1 )
        self.Y_len = np.expand_dims( np.array( self.Y_len ), 1 )

        self.cur_val_index = self.val_split
        self.cur_index = 0

    def get_batch( self, index, size ):
        input_length = self.X_len[ index : index + size ]
        label_length = self.Y_len[ index : index + size ]
        ret = { "the_input": self.X_data[ index : index + size ], 
                "the_labels": self.Y_data[ index : index + size ],
                "input_length": input_length,
                "label_length": label_length,
                "ctc" : np.zeros( [size] ) }  #dummy
        return ret

    def next_train( self ):
        while 1:
            ret = self.get_batch( self.cur_index, self.minibatch_size )
            #print( " #%d" % self.cur_index )
            self.cur_index += self.minibatch_size
            if self.cur_index >= self.val_split:
                self.cur_index = self.cur_index % 32
                (self.X_data, self.Y_data, self.X_len, self.Y_len ) = shuffle_matrices( [self.X_data, self.Y_data, self.X_len, self.Y_len ], self.val_split ) 
            yield ret

    def next_val( self ):
        while 1:
            ret = self.get_batch( self.cur_val_index, self.minibatch_size )
            #print( " #%d" % self.cur_val_index )
            self.cur_val_index += self.minibatch_size
            if self.cur_val_index >= self.num_words:
                self.cur_val_index = self.val_split + self.cur_val_index % 32
            yield ret

def dummy_func( y_true_dummy, y_pred ):
    return y_pred

def ctc_lambda_func( inputs ):
    from IPython import embed

    y_pred =        inputs["seq_layers"]
    y_true =        inputs["the_labels"]
    input_length =    inputs["input_length"]
    label_length =     inputs["label_length"]
    #embed()
    def ctc_func( y_true, y_pred, input_length, label_length ):
        import theano 
        from keras.utils import np_utils
        import ctc

        def ctc_step( y_true_step, y_pred_step, input_length_step, label_length_step ):
            y_pred_step = y_pred_step[ 0:input_length_step[0] ]
            y_true_step = y_true_step[ 0:label_length_step[0] ]
            y_true_step = np_utils.categorical_probas_to_classes( y_true_step )
            return ctc.cost( y_pred_step, y_true_step )

        ret, _ = theano.scan( 
                                fn = ctc_step, 
                                outputs_info=None,
                                sequences=[y_true, y_pred, input_length, label_length ]
                            )

        ret = ret.dimshuffle('x',0)
        return ret

    return ctc_func( y_true, y_pred, input_length, label_length )

class VizCallback ( keras.callbacks.Callback ):

    def __init__( self, test_string ):
        self.test_string = test_string

    def on_train_begin(self, logs={}):
        self.test_func = K.function( [seq_model.get_input( train=False )], [seq_model.get_output( train=False ) ] )
        self.test_in_data = np.expand_dims( font.imagify( self.test_string ), 0 )
        self.test_label = font.indexify( self.test_string )

    def on_epoch_end(self, epoch, logs={}):
        test_out = self.test_func( [self.test_in_data] )[0]
        test_out = test_out[ 0, :, self.test_label ]
        print( "\n" )
        hinton.plot( test_out,max_arr=1.)
        hinton.plot(font.imagify( self.test_string ).T[::-1].astype('float32'))
 

input_size = 8
minibatch_size = 32

datagen = DataGenerator( minibatch_size )
datagen.create_word_list( "dictionary.txt", 12480, 9984, max_word_len = 7 )

seq_model = Sequential()
seq_model.add( LSTM(  512, input_shape=[None,8], return_sequences=True ) ) 
seq_model.add( TimeDistributedDense( datagen.get_output_size() ) )
seq_model.add( Activation( "softmax" ) )

sgd = SGD(lr=0.001, decay=1e-6, momentum=0.9, nesterov=True)

graph_model = Graph()
graph_model.add_input( "the_input", input_shape = [None,8], dtype="float" )
graph_model.add_input( "the_labels", input_shape = datagen.get_output_shape(), dtype="float" )
graph_model.add_input( "input_length", input_shape = [1], dtype="int" )
graph_model.add_input( "label_length", input_shape = [1], dtype="int" )

graph_model.add_node( seq_model, "seq_layers", input = "the_input"  )
graph_model.add_node( Lambda( ctc_lambda_func ), name = "ctc", inputs = ["seq_layers", "the_labels", "input_length", "label_length" ], merge_mode="join", create_output = True )
graph_model.compile( loss = { "ctc": dummy_func }, optimizer=sgd, sample_weight_modes={ "ctc": None } )

graph_model.fit_generator( generator = datagen.next_train(), samples_per_epoch=9984, nb_epoch=50, 
                            validation_data=datagen.next_val(), nb_val_samples=2496, callbacks = [VizCallback( "test" )] )

graph_model.save_weights('weights.h5')
`

**Comment by mbhenry** [comment]
Here's a minibatch version of Shawn's CTC OCR example using Keras.  It gets roughly a 4x speedup over the non-minibatch code in theano-ctc.  The data generator class is overkill for this, but comes in handy for the image OCR application I'm writing. 

``` python
######
# Run with: THEANO_FLAGS=mode=FAST_RUN,device=gpu,floatX=float32,on_unused_input=ignore python ocr_keras.py

import sys
import random, string

import ctc
import font
import hinton

from keras import backend as K
from keras.layers.recurrent import LSTM
from keras.models import Sequential, Graph
from keras.layers.core import Dense, Dropout, Activation, TimeDistributedDense, Masking, LambdaMerge, Lambda, Layer, Merge
from keras.optimizers import SGD
from IPython import embed
from keras.utils import np_utils
import keras


import theano
import numpy as np

def shuffle_matrices( matrix_list, stop_ind = None):
    ret = []
    assert( all( [ len(i) == len(matrix_list[0] ) for i in matrix_list ] ) )
    len_val = len( matrix_list[0] )
    if stop_ind == None:
        stop_ind = len_val
    assert( stop_ind <= len_val ) 

    a = range( stop_ind )
    random.shuffle(a)
    a = a + range( stop_ind, len_val )
    for mat in matrix_list:
        ret.append( mat[a] )
    return ret

class DataGenerator( ):

    def __init__( self, minibatch_size ):
        self.minibatch_size = minibatch_size

    def time_to_categorical( self, Y, num_classes ):
        ret = np.zeros( [Y.shape[0], Y.shape[1], num_classes] )
        for i in range(Y.shape[0]):
            ret[i,:,:] = np_utils.to_categorical( Y[i,:], num_classes )
        return ret

    def get_output_size( self ):
        return len(font.chars)+1    

    def get_output_shape( self ):
        return [ None, self.get_output_size() ]

    def create_word_list( self, word_file, num_words, val_split, max_word_len = None ):
        self.word_list = []
        self.num_words = None

        assert( num_words % self.minibatch_size == 0 )
        assert( ( val_split * num_words ) % self.minibatch_size == 0 )

        with open(word_file, "rt") as f:
            for line in f:
                word = line.rstrip()
                if( max_word_len == -1 or max_word_len == None or len( word ) <= max_word_len ):
                    self.word_list.append( word )
                if( len( self.word_list ) == num_words ):
                    break

        self.num_words = num_words
        self.val_split = val_split

        self.X_data = np.ones( [self.num_words, max_word_len*8, 8 ] ) * -1
        self.Y_data = np.ones( [self.num_words, max_word_len ] ) * -1
        self.X_len = [0] * self.num_words
        self.Y_len = [0] * self.num_words

        for i, word in enumerate( self.word_list):

            self.X_len[i] = ( len( word ) ) * 8
            self.X_data[i, 0:self.X_len[i], :] = font.imagify( word )
            self.Y_len[i] = len( word ) 
            self.Y_data[i, 0:self.Y_len[i] ] = font.indexify( word )

        self.Y_data = self.time_to_categorical( self.Y_data, self.get_output_size() )
        self.X_len = np.expand_dims( np.array( self.X_len ), 1 )
        self.Y_len = np.expand_dims( np.array( self.Y_len ), 1 )

        self.cur_val_index = self.val_split
        self.cur_index = 0

    def get_batch( self, index, size ):
        input_length = self.X_len[ index : index + size ]
        label_length = self.Y_len[ index : index + size ]
        ret = { "the_input": self.X_data[ index : index + size ], 
                "the_labels": self.Y_data[ index : index + size ],
                "input_length": input_length,
                "label_length": label_length,
                "ctc" : np.zeros( [size] ) }  #dummy
        return ret

    def next_train( self ):
        while 1:
            ret = self.get_batch( self.cur_index, self.minibatch_size )
            #print( " #%d" % self.cur_index )
            self.cur_index += self.minibatch_size
            if self.cur_index >= self.val_split:
                self.cur_index = self.cur_index % 32
                (self.X_data, self.Y_data, self.X_len, self.Y_len ) = shuffle_matrices( [self.X_data, self.Y_data, self.X_len, self.Y_len ], self.val_split ) 
            yield ret

    def next_val( self ):
        while 1:
            ret = self.get_batch( self.cur_val_index, self.minibatch_size )
            #print( " #%d" % self.cur_val_index )
            self.cur_val_index += self.minibatch_size
            if self.cur_val_index >= self.num_words:
                self.cur_val_index = self.val_split + self.cur_val_index % 32
            yield ret

def dummy_func( y_true_dummy, y_pred ):
    return y_pred

def ctc_lambda_func( inputs ):
    from IPython import embed

    y_pred =        inputs["seq_layers"]
    y_true =        inputs["the_labels"]
    input_length =    inputs["input_length"]
    label_length =     inputs["label_length"]
    #embed()
    def ctc_func( y_true, y_pred, input_length, label_length ):
        import theano 
        from keras.utils import np_utils
        import ctc

        def ctc_step( y_true_step, y_pred_step, input_length_step, label_length_step ):
            y_pred_step = y_pred_step[ 0:input_length_step[0] ]
            y_true_step = y_true_step[ 0:label_length_step[0] ]
            y_true_step = np_utils.categorical_probas_to_classes( y_true_step )
            return ctc.cost( y_pred_step, y_true_step )

        ret, _ = theano.scan( 
                                fn = ctc_step, 
                                outputs_info=None,
                                sequences=[y_true, y_pred, input_length, label_length ]
                            )

        ret = ret.dimshuffle('x',0)
        return ret

    return ctc_func( y_true, y_pred, input_length, label_length )

class VizCallback ( keras.callbacks.Callback ):

    def __init__( self, test_string ):
        self.test_string = test_string

    def on_train_begin(self, logs={}):
        self.test_func = K.function( [seq_model.get_input( train=False )], [seq_model.get_output( train=False ) ] )
        self.test_in_data = np.expand_dims( font.imagify( self.test_string ), 0 )
        self.test_label = font.indexify( self.test_string )

    def on_epoch_end(self, epoch, logs={}):
        test_out = self.test_func( [self.test_in_data] )[0]
        test_out = test_out[ 0, :, self.test_label ]
        print( "\n" )
        hinton.plot( test_out,max_arr=1.)
        hinton.plot(font.imagify( self.test_string ).T[::-1].astype('float32'))


input_size = 8
minibatch_size = 32

datagen = DataGenerator( minibatch_size )
datagen.create_word_list( "dictionary.txt", 12480, 9984, max_word_len = 7 )

seq_model = Sequential()
seq_model.add( LSTM(  512, input_shape=[None,8], return_sequences=True ) ) 
seq_model.add( TimeDistributedDense( datagen.get_output_size() ) )
seq_model.add( Activation( "softmax" ) )

sgd = SGD(lr=0.001, decay=1e-6, momentum=0.9, nesterov=True)

graph_model = Graph()
graph_model.add_input( "the_input", input_shape = [None,8], dtype="float" )
graph_model.add_input( "the_labels", input_shape = datagen.get_output_shape(), dtype="float" )
graph_model.add_input( "input_length", input_shape = [1], dtype="int" )
graph_model.add_input( "label_length", input_shape = [1], dtype="int" )

graph_model.add_node( seq_model, "seq_layers", input = "the_input"  )
graph_model.add_node( Lambda( ctc_lambda_func ), name = "ctc", inputs = ["seq_layers", "the_labels", "input_length", "label_length" ], merge_mode="join", create_output = True )
graph_model.compile( loss = { "ctc": dummy_func }, optimizer=sgd, sample_weight_modes={ "ctc": None } )

graph_model.fit_generator( generator = datagen.next_train(), samples_per_epoch=9984, nb_epoch=50, 
                            validation_data=datagen.next_val(), nb_val_samples=2496, callbacks = [VizCallback( "test" )] )

graph_model.save_weights('weights.h5')
```

**Comment by shawntan** [comment]
I've written the batched version of the `inc_subtensor` approach that I replaced the matrix version with. Check it out!
